#![feature(mutex_unlock)]

[package]
name = "lifx-api-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lifx-rs = { git = "https://github.com/PixelCoda/lifx-rs.git", version = "0.1.26" }

get_if_addrs = "0.5.3"
failure = "0.1.2"
rouille = "3.5.0"

serde_json = "1.0"
serde_derive = "1.0.130"
palette = "0.2.1"
colors-transform = "0.2.11"

[dependencies.serde]
version = "1.0"
features = ["derive"]
